# Generated by Django 5.2.1 on 2025-05-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0003_alter_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
