# Generated by Django 5.2.1 on 2025-05-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0005_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='rating',
        ),
    ]
