# Generated by Django 5.2.1 on 2025-05-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0007_alter_bid_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('amount',)},
        ),
    ]
