# Generated by Django 5.2.1 on 2025-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0008_alter_bid_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='thumbnail',
            field=models.URLField(max_length=1000),
        ),
    ]
